# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "Account Move CSV Import DTVF",
    "summary": "Import account moves generated by external software",
    "author": "Odoo Community Association (OCA)",
    "version": "16.0.1.0.0",
    "category": "Accounting",
    "depends": ["account"],
    "website": "https://github.com/OCA/l10n-germany",
    "demo": [],
    "external_dependencies": {"python": ["unicodecsv"]},
    "data": [
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "wizard/import_move_view.xml",
    ],
    "installable": True,
    "auto_install": False,
    "license": "AGPL-3",
}
