# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "Account Move CSV Import DTVF",
    "summary": "Import account moves generated by external software",
    "description": "This module is used to import account moves from a CSV file.",
    "version": "12.0.1.0.0",
    "category": "Accounting",
    "depends": ["account"],
    "demo": [],
    "external_dependencies": {"python": ["unicodecsv"]},
    "data": [
        "data/sequence.xml",
        "wizard/import_move_view.xml",
    ],
    "installable": True,
    "auto_install": False,
    "license": "AGPL-3",
}
