[project]
name = "odoo-addons-oca-l10n-germany"
version = "18.0.20260713.1"
dependencies = [
    "odoo-addon-datev_export==18.0.*",
    "odoo-addon-datev_export_dtvf==18.0.*",
    "odoo-addon-datev_export_xml==18.0.*",
    "odoo-addon-datev_import_csv_dtvf==18.0.*",
    "odoo-addon-hr_expense_meal_allowance==18.0.*",
    "odoo-addon-l10n_de_accounting_app==18.0.*",
    "odoo-addon-l10n_de_location_nuts==18.0.*",
    "odoo-addon-l10n_de_mis_reports==18.0.*",
    "odoo-addon-l10n_de_partner_company_type==18.0.*",
    "odoo-addon-l10n_de_tax_statement==18.0.*",
    "odoo-addon-l10n_de_tax_statement_zm==18.0.*",
    "odoo-addon-l10n_din5008_company_header_country_invisible==18.0.*",
    "odoo-addon-l10n_din5008_move_name==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
